Import systemd_215-12.debian.tar.xz
Remove all files and import latest packaging version, but
with debian/patches removed.

diff --git a/debian/rules b/debian/rules
--- a/debian/rules
+++ b/debian/rules
@@ -5,43 +5,72 @@
 
 DEB_HOST_MULTIARCH ?= $(shell dpkg-architecture -qDEB_HOST_MULTIARCH)
 
+ifneq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+BOOTSTRAP_DH_FLAGS := -Ngir1.2-gudev-1.0 -Nlibgudev-1.0-0 -Nlibgudev-1.0-dev
+endif
+
 CONFFLAGS = \
 	--with-rootprefix= \
 	--with-rootlibdir=/lib/$(DEB_HOST_MULTIARCH) \
+	--with-zshcompletiondir=/usr/share/zsh/vendor-completions \
 	--with-sysvinit-path=/etc/init.d \
 	--with-sysvrcnd-path=/etc \
 	--with-firmware-path=/lib/firmware \
 	--with-debug-shell=/bin/bash \
-	--enable-libcryptsetup \
-	--enable-tcpwrap \
-	--enable-vconsole \
+	--with-telinit=/lib/sysvinit/telinit \
 	--disable-coredump \
 	--disable-efi \
 	--disable-myhostname \
-	--disable-silent-rules
+	--disable-vconsole \
+	--disable-microhttpd \
+	--disable-sysusers \
+	--disable-silent-rules \
+	--with-ntp-servers="0.debian.pool.ntp.org 1.debian.pool.ntp.org 2.debian.pool.ntp.org 3.debian.pool.ntp.org"  \
+	--with-system-uid-max=999 \
+	--with-system-gid-max=999
+
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+CONFFLAGS += --enable-libcryptsetup
+endif
 
 CONFFLAGS_deb = \
 	--enable-selinux \
 	--enable-introspection \
-	--enable-gtk-doc
+	--enable-gtk-doc \
+	--enable-compat-libs \
+	PYTHON=python3 \
+	$(NULL)
 
 CONFFLAGS_udeb = \
+	--disable-libcryptsetup \
+	--disable-pam \
+	--disable-audit \
 	--disable-selinux \
+	--disable-smack \
+	--disable-ima \
 	--disable-introspection \
 	--disable-gtk-doc \
 	--disable-binfmt \
 	--disable-readahead \
 	--disable-bootchart \
 	--disable-quotacheck \
+	--disable-tmpfiles \
 	--disable-randomseed \
+	--disable-backlight \
 	--disable-logind \
+	--disable-machined \
 	--disable-hostnamed \
 	--disable-timedated \
+	--disable-networkd \
+	--disable-timesyncd \
 	--disable-localed \
+	--disable-resolved \
 	--disable-polkit \
 	--disable-acl \
-	--disable-xattr \
+	--disable-gcrypt \
 	--disable-gudev \
+	--disable-rfkill \
+	--disable-multi-seat-x \
 	--disable-manpages \
 	--without-python
 
@@ -67,6 +96,12 @@ override_dh_auto_clean:
 	rm -rf debian/install/
 	# remove pre-generated man pages so they are rebuilt
 	rm -f man/*.[13578]
+	# remove pre-generated rules and unit files so they are rebuilt
+	rm -f rules/99-systemd.rules \
+		units/emergency.service \
+		units/systemd-udevd.service \
+		units/systemd-udev-settle.service \
+		units/systemd-udev-trigger.service
 	# remove Python byte code files
 	rm -f *.pyc
 
@@ -76,11 +111,30 @@ override_dh_install:
 	rm -f debian/install/*/var/log/README
 	rm -f debian/install/*/etc/init.d/README
 	rm -f debian/install/*/usr/share/man/man8/kernel-install.8
+	rm -f debian/install/*/usr/bin/kernel-install
+	rm -f debian/install/*/usr/share/zsh/vendor-completions/_kernel-install
+	rm -f debian/install/*/usr/share/bash-completion/completions/kernel-install
+	rm -rf debian/install/*/usr/lib/kernel/install.d
 	rm -rf debian/install/*/etc/rpm/
+	rm -rf debian/install/*/usr/lib/rpm/
 	rm -rf debian/install/*/etc/kernel/
+	rm -f debian/install/*/usr/lib/sysctl.d/50-default.conf
 	find debian/install/ -name '*.la' -delete
+	# remove files related to factory-reset feature
+	find debian/install/ \( -name 'systemd-update-done*' -o \
+		-name systemd-journal-catalog-update.service -o \
+		-name systemd-udev-hwdb-update.service -o \
+		-name ldconfig.service -o \
+		-name etc.conf \) -delete
+	# remove .so for deprecated compatibility libraries
+	rm -f debian/install/*/usr/lib/*/libsystemd-daemon.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-login.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-id128.so
+	rm -f debian/install/*/usr/lib/*/libsystemd-journal.so
+	# remove symlinks enabling default-on services
+	rm -rf debian/install/*/etc/systemd/system/*.target.wants/
 	dh_install -pudev-udeb -plibudev1-udeb --sourcedir=debian/install/udeb
-	dh_install -Nudev-udeb -Nlibudev1-udeb --sourcedir=debian/install/deb
+	dh_install $(BOOTSTRAP_DH_FLAGS) -Nudev-udeb -Nlibudev1-udeb --sourcedir=debian/install/deb --fail-missing
 	# install some files manually, --sourcedir makes that necessary
 	# udev-udeb
 	install -D --mode=755 debian/extra/udev.startup \
@@ -89,22 +143,15 @@ override_dh_install:
 		debian/udev-udeb/usr/lib/base-installer.d/05udev
 	mkdir -p debian/udev-udeb/lib/udev/rules.d/
 	install -D --mode=644 \
-		debian/extra/rules/50-udev-default.rules \
-		debian/extra/rules/60-persistent-storage.rules \
-		debian/extra/rules/75-cd-aliases-generator.rules \
+		debian/extra/rules/73-idrac.rules \
 		debian/extra/rules/75-persistent-net-generator.rules \
-		debian/extra/rules/80-drivers.rules \
-		debian/extra/rules/91-permissions.rules \
 		debian/udev-udeb/lib/udev/rules.d/
-	install -D --mode=644 debian/extra/links.conf \
-		debian/udev-udeb/etc/udev/links.conf
 	mkdir -p debian/udev-udeb/lib/udev
 	install -D --mode=644 \
 		debian/extra/hotplug.functions \
 		debian/extra/rule_generator.functions \
 		debian/udev-udeb/lib/udev/
 	install -D --mode=755 \
-		debian/extra/write_cd_rules \
 		debian/extra/write_net_rules \
 		debian/udev-udeb/lib/udev/
 	# udev: initramfs-tools support
@@ -117,8 +164,6 @@ override_dh_install:
 	# udev: debian specific rules and helpers
 	install -D --mode=644 debian/extra/rules/* \
 		debian/udev/lib/udev/rules.d/
-	install -D --mode=644 debian/extra/links.conf \
-		debian/udev/etc/udev/
 	install -D --mode=644 debian/extra/fbdev-blacklist.conf \
 		debian/udev/etc/modprobe.d/fbdev-blacklist.conf
 	install -D --mode=644 \
@@ -126,11 +171,10 @@ override_dh_install:
 		debian/extra/rule_generator.functions \
 		debian/udev/lib/udev/
 	install -D --mode=755 \
-		debian/extra/create_static_nodes \
 		debian/extra/dsl-modem.agent \
 		debian/extra/logger.agent \
 		debian/extra/net.agent \
-		debian/extra/write_cd_rules \
+		debian/extra/udev-finish \
 		debian/extra/write_net_rules \
 		debian/udev/lib/udev/
 	# systemd
@@ -139,12 +183,29 @@ override_dh_install:
 		debian/systemd/lib/lsb/init-functions.d/40-systemd
 	install --mode=644 debian/tmpfiles.d/debian.conf \
 		debian/systemd/usr/lib/tmpfiles.d/
-	install --mode=644 debian/ifup@.service \
-		debian/units/run-lock.mount debian/units/run-user.mount \
+	install --mode=644 debian/debian-fixup.service debian/ifup@.service debian/extra/getty-static.service \
 		debian/systemd/lib/systemd/system/
+	install -D --mode=644 debian/extra/network-pre.conf \
+		debian/systemd/lib/systemd/system/networking.service.d/network-pre.conf
+	install --mode=644 debian/extra/udev-finish.service \
+		debian/udev/lib/systemd/system/
+	ln -s ../udev-finish.service debian/udev/lib/systemd/system/sysinit.target.wants/
+	install --mode=755 debian/debian-fixup \
+		debian/systemd/lib/systemd/
+	# Make sure the runlevel services are known by systemd so their targets
+	# get launches. See https://bugzilla.redhat.com/show_bug.cgi?id=1002806
+	for t in poweroff rescue multi-user graphical reboot; do \
+		mkdir -p debian/systemd/lib/systemd/system/$${t}.target.wants;\
+		ln -s ../systemd-update-utmp-runlevel.service \
+			debian/systemd/lib/systemd/system/$${t}.target.wants ;\
+	done
+	# man files for example code in /usr/share/doc
+	mkdir -p debian/systemd/usr/share/man/man3/
+	mv debian/libsystemd-dev/usr/share/man/man3/sd-readahead.3 \
+		debian/libsystemd-dev/usr/share/man/man3/sd_readahead.3 \
+		debian/systemd/usr/share/man/man3/
 	install --mode=755 debian/systemd-logind-launch \
 		debian/systemd/lib/systemd/
-	echo "LANG=en_US.utf8" > debian/systemd/etc/locale.conf
 	# remove duplicates
 	# files shipped by systemd-sysv / sysvinit
 	rm debian/systemd/usr/share/man/man1/init.1
@@ -166,7 +227,9 @@ override_dh_install:
 	# files shipped by udev / bash-completion
 	rm debian/systemd/usr/share/bash-completion/completions/udevadm
 	# files systemd by cryptsetup
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
 	rm debian/systemd/usr/share/man/man5/crypttab.5
+endif
 	# files shipped by systemd
 	rm debian/udev/lib/udev/rules.d/70-uaccess.rules
 	rm debian/udev/lib/udev/rules.d/73-seat-late.rules
@@ -176,6 +239,8 @@ override_dh_install:
 # use symlinked doc directories as the old udev package did
 override_dh_installdocs:
 	dh_installdocs -pudev -plibudev-dev --link-doc=libudev1
+	# we have to manually install udev's README for the above
+	install -D --mode 644 debian/udev.README.Debian debian/libudev1/usr/share/doc/libudev1/README.Debian
 	dh_installdocs -pgir1.2-gudev-1.0 -plibgudev-1.0-dev --link-doc=libgudev-1.0-0
 	dh_installdocs --remaining-packages
 
@@ -185,6 +250,13 @@ override_dh_installinit:
 	dh_installinit --name=udevtrigger --no-start
 	dh_installinit --name=udevmonitor --no-start
 	dh_installinit --name=udev-fallback-graphics --no-start
+
+# The SysV compat tools (which are symlinks to systemctl) are
+# quasi-essential, so add its dependencies to Pre-Depends
+# https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=753589
+override_dh_shlibdeps:
+	dh_shlibdeps -psystemd -- -dPre-Depends -edebian/systemd/bin/systemctl -dDepends
+	dh_shlibdeps --remaining-packages
 
 override_dh_makeshlibs:
 	dh_makeshlibs -plibudev1 --add-udeb=libudev1-udeb
@@ -198,5 +270,23 @@ autoreconf:
 override_dh_autoreconf:
 	dh_autoreconf debian/rules -- autoreconf
 
+override_dh_strip:
+	dh_strip --dbg-package=systemd-dbg
+
+override_dh_auto_test:
+ifeq (, $(findstring nocheck, $(DEB_BUILD_OPTIONS)))
+	# some tests hang under fakeroot, so disable fakeroot
+	echo "01234567890123456789012345678901" > build-deb/machine-id
+	env -u LD_PRELOAD SYSTEMD_MACHINE_ID_PATH=$(CURDIR)/build-deb/machine-id \
+		make -C build-deb check || ( \
+		cd build-deb; \
+		for f in test-*.log; do echo "==== $$f ===="; cat $$f; done; \
+		exit 0; )  # replace with 1 to make failures fatal
+endif
+
 %:
-	dh $@ --with autoreconf,gir,python2
+ifeq (,$(findstring stage1,$(DEB_BUILD_PROFILES)))
+	dh $@ --with autoreconf,gir,python3 --parallel
+else
+	dh $@ --with autoreconf,python3 $(BOOTSTRAP_DH_FLAGS)
+endif
