Import packaging for version 237-4
This is a clean import from Debian Buster minus the debian/patches
directory -- all downstream patches have been applied to the main
branch.

https://phabricator.endlessm.com/T21201

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -28,12 +28,15 @@ if [ "$1" = "triggered" ]; then
     exit 0
 fi
 
-# Enable getty and remote-fs.target by default on new installs, and on
-# upgrades from old systemd versions (where the symlinks included as deb
-# content, and will thus have been removed by dpkg during the upgrade).
-if dpkg --compare-versions "$2" lt "214-1"; then
+# Enable getty and remote-fs.target by default on new installs
+if [ -z "$2" ]; then
     systemctl enable getty@tty1.service || true
     systemctl enable remote-fs.target || true
+fi
+
+# Enable timesyncd by default on new installs installs and upgrades
+if dpkg --compare-versions "$2" lt "218-11~"; then
+    systemctl enable systemd-timesyncd.service || true
 fi
 
 # Enable ondemand by default on new installs installs and upgrades
@@ -42,7 +45,7 @@ if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" l
 fi
 
 # Do a one-time migration of the local time setting
-if dpkg --compare-versions "$2" lt "33-1"; then
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -52,13 +55,7 @@ if dpkg --compare-versions "$2" lt "33-1"; then
 fi
 
 # Do a one-time migration of the TMPTIME setting
-if dpkg --compare-versions "$2" lt "204-9"; then
-    # Fix up potentially broken tmp.conf, see Debian#738862
-    if [ -e /etc/tmpfiles.d/tmp.conf ]; then
-        sed -i '/^# Clear \/var\/tmp/d' /etc/tmpfiles.d/tmp.conf
-        sed -i 's,^\(d /var/tmp\),#\1,g' /etc/tmpfiles.d/tmp.conf
-    fi
-
+if [ -z "$2" ]; then
     if [ -f /etc/default/rcS ]; then
         . /etc/default/rcS
     fi
@@ -76,29 +73,45 @@ EOF
     fi
 fi
 
+# Do a one-time migration of the RAMTMP setting
+if [ -z "$2" ]; then
+    if [ -f /etc/default/rcS ]; then
+        . /etc/default/rcS
+    fi
+    if [ -f /etc/default/tmpfs ]; then
+        . /etc/default/tmpfs
+    fi
+    if [ "$RAMTMP" = "yes" ]; then
+        # systemctl enable will work even when systemd is not the active PID 1.
+        if [ ! -e /etc/systemd/system/tmp.mount ]; then
+            cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
+            systemctl enable tmp.mount || true
+        fi
+    fi
+fi
+
 # Create /etc/machine-id
 systemd-machine-id-setup
 
 # Setup system users and groups
-addgroup --system systemd-journal
+addgroup --quiet --system systemd-journal
 
-adduser --quiet --system --group --no-create-home --home /run/systemd \
-    --gecos "systemd Bus Proxy" systemd-bus-proxy
+adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
+    --gecos "systemd Network Management" systemd-network
+adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
+    --gecos "systemd Resolver" systemd-resolve
 
 # Initial update of the Message Catalogs database
 _update_catalog
-
-# Re-run systemctl enable for any service that was enabled when preinst was run.
-if dpkg --compare-versions "$2" ge "204" && [ -e /run/systemd/was-enabled ]; then
-    while read UNIT ; do
-        systemctl enable $UNIT || true
-    done </run/systemd/was-enabled || true
-fi
 
 if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
+    _systemctl try-restart systemd-networkd.service || true
+    _systemctl try-restart systemd-resolved.service || true
+    _systemctl try-restart systemd-timesyncd.service || true
+    _systemctl try-restart systemd-journald.service || true
 fi
 
 # Cleanup hwclock-save.service, which was shipped in jessie.
@@ -107,6 +120,18 @@ if dpkg --compare-versions "$2" lt-nl "228-5~"; then
        rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
        rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
    done
+fi
+
+if dpkg --compare-versions "$2" lt-nl "235-3~"; then
+    # systemd-bus-proxyd got dropped before stretch, and never created any file
+    deluser --system systemd-bus-proxy || true
+fi
+
+if dpkg --compare-versions "$2" lt-nl "236-1~"; then
+    # Clean up old /var/lib/systemd/clock on upgrade.
+    # The clock file used by systemd-timesyncd is now stored in
+    # StateDirectory=systemd/timesync.
+    rm -f /var/lib/systemd/clock
 fi
 
 #DEBHELPER#
