Import packaging for version 232-25+deb9u1
This is a clean import from Debian Stretch minus the content of
debian/patches, which has been applied to the main branch (99 patches).

https://phabricator.endlessm.com/T15367

diff --git a/debian/systemd.postinst b/debian/systemd.postinst
--- a/debian/systemd.postinst
+++ b/debian/systemd.postinst
@@ -21,7 +21,7 @@ if [ "$1" = "triggered" ]; then
                 _update_catalog
                 ;;
             /etc/init.d)
-                _systemctl daemon-reload
+                _systemctl daemon-reload || true
                 ;;
         esac
     done
@@ -39,6 +39,11 @@ fi
 # Enable timesyncd by default on new installs installs and upgrades
 if dpkg --compare-versions "$2" lt "218-11~"; then
     systemctl enable systemd-timesyncd.service || true
+fi
+
+# Enable ondemand by default on new installs installs and upgrades
+if [ -e /lib/systemd/system/ondemand.service ] && dpkg --compare-versions "$2" lt "231-7~"; then
+    systemctl enable ondemand.service || true
 fi
 
 # Do a one-time migration of the local time setting
@@ -76,6 +81,23 @@ EOF
     fi
 fi
 
+# Do a one-time migration of the RAMTMP setting
+if dpkg --compare-versions "$2" lt "204-8"; then
+    if [ -f /etc/default/rcS ]; then
+        . /etc/default/rcS
+    fi
+    if [ -f /etc/default/tmpfs ]; then
+        . /etc/default/tmpfs
+    fi
+    if [ "$RAMTMP" = "yes" ]; then
+        # systemctl enable will work even when systemd is not the active PID 1.
+        if [ ! -e /etc/systemd/system/tmp.mount ]; then
+            cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
+            systemctl enable tmp.mount || true
+        fi
+    fi
+fi
+
 # Create /etc/machine-id
 systemd-machine-id-setup
 
@@ -83,17 +105,30 @@ systemd-machine-id-setup
 addgroup --system systemd-journal
 
 adduser --quiet --system --group --no-create-home --home /run/systemd \
+    --gecos "systemd Time Synchronization" systemd-timesync
+adduser --quiet --system --group --no-create-home --home /run/systemd/netif \
+    --gecos "systemd Network Management" systemd-network
+adduser --quiet --system --group --no-create-home --home /run/systemd/resolve \
+    --gecos "systemd Resolver" systemd-resolve
+adduser --quiet --system --group --no-create-home --home /run/systemd \
     --gecos "systemd Bus Proxy" systemd-bus-proxy
 
 # Initial update of the Message Catalogs database
 _update_catalog
 
-# Make systemd-detect-virt utility usable for non-root users
-setcap cap_dac_override,cap_sys_ptrace=ep /usr/bin/systemd-detect-virt || true
-
 # Re-run systemctl enable for any service that was enabled when preinst was run.
 if dpkg --compare-versions "$2" ge "204" && [ -e /run/systemd/was-enabled ]; then
     while read UNIT ; do
+        # 220-6 stopped shipping tmp.mount, transition it on machines which had
+        # it enabled
+        if [ "$UNIT" = tmp.mount ] && dpkg --compare-versions "$2" lt-nl "220-6~"; then
+            if [ ! -e /etc/systemd/system/tmp.mount ]; then
+                echo "moving enabled tmp.mount to /etc/systemd/system/..."
+                cp /usr/share/systemd/tmp.mount /etc/systemd/system/tmp.mount
+                # clean up the symlink, to have it re-created below
+                systemctl disable $UNIT
+            fi
+        fi
         systemctl enable $UNIT || true
     done </run/systemd/was-enabled || true
 fi
@@ -102,6 +137,9 @@ if [ -n "$2" ]; then
     _systemctl daemon-reexec || true
     # don't restart logind; this can be done again once this gets implemented:
     # https://github.com/systemd/systemd/issues/1163
+    _systemctl try-restart systemd-networkd.service || true
+    _systemctl try-restart systemd-resolved.service || true
+    _systemctl try-restart systemd-timesyncd.service || true
 fi
 
 # Cleanup hwclock-save.service, which was shipped in jessie.
@@ -110,12 +148,6 @@ if dpkg --compare-versions "$2" lt-nl "228-5~"; then
        rm -f /etc/systemd/system/${t}.target.wants/hwclock-save.service
        rmdir --ignore-fail-on-non-empty /etc/systemd/system/${t}.target.wants 2> /dev/null || true
    done
-fi
-
-# start systemd-networkd-resolvconf-update.path on first install/upgrade if
-# required
-if _systemctl is-active --quiet resolvconf; then
-    _systemctl start systemd-networkd-resolvconf-update.path || true
 fi
 
 #DEBHELPER#
